[project]
name = "lunarastro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.2.0",
    "pyswisseph>=2.10.3.2",
    "streamlit>=1.46.1",
]

[dependency-groups]
dev = [
    "watchdog>=6.0.0",
]
